ethnicity_is_indian = {
    'Italian Americans': 0,
    'Yugoslavs': 0,
    'Irish people': 0,
    'German Canadians': 0,
    'Serbian Canadians': 0,
    'Swedish Americans': 0,
    'African Americans': 0,
    'Irish Americans': 0,
    'Italians': 0,
    'Taiwanese Americans': 0,
    'Chinese Americans': 0,
    'English people': 0,
    'British': 0,
    'Jewish people': 0,
    'English Americans': 0,
    'Ecuadorian Americans': 0,
    'Scottish Americans': 0,
    'Hongkongers': 0,
    'German Americans': 0,
    'Japanese Americans': 0,
    'Germans': 0,
    'Bolivian Americans': 0,
    'Malaysian Chinese': 0,
    'Mexicans': 0,
    'Ukrainian Canadians': 0,
    'Koikküla': 0,
    'Manx people': 0,
    'Armenian Americans': 0,
    'British Chinese': 0,
    'Chinese Singaporeans': 0,
    'Welsh people': 0,
    'White British': 0,
    'Indigenous peoples of the Americas': 0,
    'Black Britons': 0,
    'British Jamaicans': 0,
    'Norwegians': 0,
    'Hungarian Americans': 0,
    'Hungarians': 0,
    'Serbian Australians': 0,
    'British Americans': 0,
    'White Americans': 0,
    'French': 0,
    'Swiss': 0,
    'Dutch Americans': 0,
    'French Americans': 0,
    'Samoan Americans': 0,
    'Bahamian Americans': 0,
    'Ashkenazi Jews': 0,
    'Serbian Americans': 0,
    'Scotch-Irish Americans': 0,
    'Mexican Americans': 0,
    'Russian Americans': 0,
    'Portuguese Americans': 0,
    'White people': 0,
    'Astún': 0,
    'Afghans in India': 0,
    'Romanichal': 0,
    'French Canadians': 0,
    'Cuban Americans': 0,
    'Scandinavian Americans': 0,
    'Israelis': 0,
    'Indians': 1,
    'Scottish people': 0,
    'Sicilian Americans': 0,
    'Austrian Americans': 0,
    'Spaniards': 0,
    'Swedes': 0,
    'Lumbee': 0,
    'Croatian Americans': 0,
    'Croatian Australians': 0,
    'English Australian': 0,
    'Irish migration to Great Britain': 0,
    'Polish Americans': 0,
    'American Jews': 0,
    'Danish Americans': 0,
    'Stateside Puerto Ricans': 0,
    'Kiwi': 0,
    'Indian Americans': 1,
    'European Americans': 0,
    'Bengali': 1,
    'Mohawk': 0,
    'Dutch': 0,
    'Koreans': 0,
    'Japanese': 0,
    'Italian Australians': 0,
    'names of the Greeks': 0,
    'Sámi people': 0,
    'Lebanese Americans': 0,
    'Lithuanian Americans': 0,
    'Puerto Ricans': 0,
    'Syrian Americans': 0,
    'Native Americans': 0,
    'Telugu Brahmins': 1,
    'Somalis': 0,
    'Latin American British': 0,
    'Canadian Americans': 0,
    'Chilean Americans': 0,
    'Cajun': 0,
    'Albanian Americans': 0,
    'Tamil': 1,
    'Romani people': 0,
    'Spanish Americans': 0,
    'Xhosa people': 0,
    'British Pakistanis': 0,
    'Blackfoot Confederacy': 0,
    'Afro Trinidadians and Tobagonians': 0,
    'Castilians': 0,
    'Mandinka people': 0,
    'White Africans of European ancestry': 0,
    'Punjabi diaspora': 1,
    'Greek Americans': 0,
    'Black people': 0,
    'Louisiana Creole people': 0,
    'Armenians': 0,
    'Asian Americans': 0,
    'Kayastha': 1,
    'Anglo-Celtic Australians': 0,
    'Americans': 0,
    'Austrians in the United Kingdom': 0,
    'Australian Americans': 0,
    'Punjabis': 1,
    'Taiwanese people': 0,
    'Croatian Canadians': 0,
    'Romani people in Spain': 0,
    'Basque people': 0,
    'Hispanic and Latino Americans': 0,
    'Javanese': 0,
    'Filipino people': 0,
    'Ukrainian Americans': 0,
    'Wolof people': 0,
    'Scottish Canadians': 0,
    'Haitian Americans': 0,
    'Sudanese Arabs': 0,
    'Aboriginal Australians': 0,
    'Spanish people of Filipino ancestry': 0,
    'Dominican Americans': 0,
    'Kapampangan people': 0,
    'Chinese Filipino': 0,
    'Irish Canadians': 0,
    'Poles': 0,
    'Russians': 0,
    'Asian people': 0,
    'Venezuelans': 0,
    'Parsi': 1,
    'Icelanders': 0,
    'Sri Lankan Tamil diaspora': 1,
    'Greeks in the United Kingdom': 0,
    'Cubans': 0,
    'Ojibwe': 0,
    'Tatars': 0,
    'British Indian': 1,
    'Marathi people': 1,
    'Egyptians': 0,
    'Black Irish': 0,
    'Tamil Brahmin': 1,
    'Italians in the United Kingdom': 0,
    'Maori': 0,
    'Czech Americans': 0,
    'Ghanaian Americans': 0,
    'Choctaw': 0,
    'Pashtuns': 0,
    'Kanyakubja Brahmins': 1,
    'Nepali Indian': 1,
    'Australians': 0,
    'White Latin American': 0,
    'Anglo-Irish people': 0,
    'Ukrainians': 0,
    'Hindkowans': 0,
    'Irish Australians': 0,
    'Pakistanis': 0,
    'Pacific Islander Americans': 0,
    'Czechs': 0,
    'multiracial American': 0,
    'Filipino Americans': 0,
    'Malayali': 1,
    'Iranian peoples': 0,
    'Rajput': 1,
    'Filipino mestizo': 0,
    'Jaat': 1,
    'Tibetan people': 0,
    'Chinese Canadians': 0,
    'Hispanic': 0,
    'Arab Americans': 0,
    'Telugu people': 1,
    'Galicians': 0,
    'Cambodian Americans': 0,
    'Kannada people': 1,
    'Kashmiri Pandit': 1,
    'Serbs in the United Kingdom': 0,
    'Brahmin': 1,
    'Moroccans': 0,
    'Thai Chinese': 0,
    'Panamanian Americans': 0,
    'Welsh Americans': 0,
    'Lebanese people': 0,
    'Baltic Russians': 0,
    'Danes': 0,
    'Mizrahi Jews': 0,
    'Serbs of Bosnia and Herzegovina': 0,
    'Copts': 0,
    'Latvians': 0,
    'Bihari people': 1,
    'Austrians': 0,
    'Bulgarian Canadians': 0,
    'Dutch Canadians': 0,
    'Argentines': 0,
    'Arabs in Bulgaria': 0,
    'French Chilean': 0,
    'Scottish Australians': 0,
    'Palestinians in the United States': 0,
    'Sri Lankan Tamils': 1,
    'Croats': 0,
    'Slovak Americans': 0,
    'Gujarati people': 1,
    'Sioux': 0,
    'Indonesian Americans': 0,
    'Pakistani Canadians': 0,
    'Tulu people': 1,
    'Nigerian Americans': 0,
    'Hondurans': 0,
    'Portuguese': 0,
    'Ryukyuan people': 0,
    'Pakistani Americans': 0,
    'Korean Americans': 0,
    'Persians': 0,
    'Sindhis': 1,
    'Niyogi': 1,
    'Hindu': 1,
    'Sudanese Australians': 0,
    'Sephardi Jews': 0,
    'Rohilla': 1,
    'Québécois': 0,
    'Danish Canadians': 0,
    'Arabs': 0,
    'Slovaks': 0,
    'Bulgarians': 0,
    'Greek Canadians': 0,
    'African-American Jews': 0,
    'Dinka people': 0,
    'Catalans': 0,
    'Swedish Australian': 0,
    'Brazilians': 0,
    'Manchu': 0,
    'Polish Australians': 0,
    'Italian Canadians': 0,
    'Akan people': 0,
    'British Jews': 0,
    'Colombian Americans': 0,
    'Finnish Americans': 0,
    'Native Hawaiians': 0,
    'Afrikaners': 0,
    'White South Africans': 0,
    'Finns': 0,
    'Serbs of Croatia': 0,
    'Peruvians in the United Kingdom': 0,
    'Cree': 0,
    'Iranians in the United Kingdom': 0,
    'Yoruba people': 0,
    'Vietnamese Americans': 0,
    'Bosnians': 0,
    'Criollo people': 0,
    'Cheyennes': 0,
    'Lao people': 0,
    'Afro-Asians': 0,
    'Georgians': 0,
    'Khatri': 1,
    'First Nations': 0,
    'Sikh': 1,
    'Muhajir': 0,
    'Polish Canadians': 0,
    'Acadians': 0,
    'Scania tephra': 0,
    'British African-Caribbean people': 0,
    'Ossetians': 0,
    'Estonians': 0,
    'Saman': 1,
    'Colombian Australian': 0,
    'Arab Mexican': 0,
    'Pathani': 1,
    'Uruguayans': 0,
    'Israeli Americans': 0,
    'Zhuang people': 0,
    'Chitrapur Saraswat Brahmin': 1,
    'Lithuanian Jews': 0,
    'Ghanaian': 0,
    'Latino': 0,
    'Brazilian Americans': 0,
    'Lebanese Mexicans': 0,
    'Omaha Tribe of Nebraska': 0,
    'Nair': 1,
    'Jatt Sikh': 1,
    'Sri Lankan Americans': 1,
    'Chaliyan': 1,
    'Ilocano': 0,
    'Iranian Americans': 0,
    'Gibraltarian people': 0,
    'Burmese Americans': 0,
    'Poles in the United Kingdom': 0,
    'Indo Caribbeans': 0,
    'Rusyn American': 0,
    'Gaud Saraswat Brahmin': 1,
    'Moroccan Jews': 0,
    'British Nigerian': 0,
    'Israeli Jews': 0,
    'Chettiar': 1,
    'Samoan New Zealanders': 0,
    'Italian Brazilians': 0,
    'Indian Australian': 1,
    'Latvian Americans': 0,
    'Honduran Americans': 0,
    'Sierra Leoneans in the United Kingdom': 0,
    'Berber': 0,
    'Inuit': 0,
    'Koryo-saram': 0,
    'Slavs': 0,
    'Thai Americans': 0,
    'Aromanians': 0,
    'Bengali Hindus': 1,
    'Czech Australians': 0,
    'Serbs in North Macedonia': 0,
    'Slovenes': 0,
    'South African Americans': 0,
    'Sherpa': 0,
    'Black Canadians': 0,
    'Guyanese Americans': 0,
    'Métis': 0,
    'Hmong Americans': 0,
    'Kashmiri people': 1,
    'Azerbaijanis': 0,
    'Welsh Italians': 0,
    'Eurasian': 0,
    'Indo-Canadians': 1,
    'Salvadoran Americans': 0,
    'African people': 0,
    'Apache': 0,
    'Chileans': 0,
    'Aceh': 0,
    'Russian Canadians': 0,
    'Colombians': 0,
    'Kabyle people': 0,
    'Iraqi Americans': 0,
    'Indo-Guyanese': 0,
    'Luxembourgish Americans': 0,
    'Lebanese people in the United Kingdom': 0,
    'Tejano': 0,
    'Belgians': 0,
    'Iroquois': 0,
    'Vietnamese people': 0,
    'Dutch Australian': 0,
    'Afro-Guyanese': 0,
    'Iranian Canadians': 0,
    'Afro-Cuban': 0,
    'British Asians': 0,
    'Dene': 0,
    'Iñupiaq people': 0,
    'Kurds': 0,
    'Barbadian Americans': 0,
    'Konkani people': 1,
    'Aymara': 0,
    'Armenians in Italy': 0,
    'culture of Palestine': 0,
    'Romanian Americans': 0,
    'Turkish Americans': 0,
    'Muslim': 0,
    'Bosniaks': 0,
    'Indian diaspora': 1,
    'Swedish-speaking population of Finland': 0,
    'Venezuelan Americans': 0,
    'Thai people': 0,
    'Soviet people': 0,
    'Albanians': 0,
    'Agrawal': 1,
    'Bhutia': 1,
    'Swedish Canadians': 0,
    'Nez Perce': 0,
    'Slovene Americans': 0,
    'Greek Australians': 0,
    'Filipino people of Spanish ancestry': 0,
    'German Brazilians': 0,
    'Armenians of Russia': 0,
    'Malagasy people': 0,
    'Oneida': 0,
    'Japanese Brazilians': 0,
    'Corsicans': 0,
    'Hutsuls': 0,
    'Transylvanian Saxons': 0,
    'Canadians in the United Kingdom': 0,
    'Karnataka Brahmins': 1,
    'multiracial people': 0,
    'Moroccan Americans': 0,
    'Bunt (RAJPUT)': 1,
    'Chinese Jamaicans': 0,
    'Tamil Americans': 1,
    'Black Hispanic and Latino Americans': 0,
    'Assyrian people': 0,
    'Canadian Australian': 0,
     'Ezhava': 1,
    'Anglo-Indian people': 1,
    'Italian immigration to Mexico': 0,
    'Mohyal': 1,
    'Chileans in the United Kingdom': 0,
    'Romanians': 0,
    'Indian diaspora in France': 1,
    'Ho-Chunk': 0,
    'Chinese Indonesians': 0,
    'Greek Cypriots': 0,
    'peoples of the Caucasus': 0,
    'Dogra': 1,
    'Mangaloreans': 1,
    'Filipino Australians': 0,
    'Bohemian People': 0,
    'Spaniards in Mexico': 0,
    'English Canadians': 0,
    'Bangladeshi Americans': 0,
    'Goans': 1,
    'Dalmatian Italians': 0,
    'Marwari people': 1,
    'Buryats': 0,
    'French-speaking Quebecer': 0,
    'Gin people': 0,
    'Sierra Leone Creole people': 0,
    'Greeks in South Africa': 0,
    'Dalit': 1,
    'Han Chinese people': 0,
    'Bengali Brahmins': 1
}